# Generated by Django 3.0.6 on 2020-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0002_auto_20200521_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_post_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
