# Generated by Django 3.0.6 on 2020-05-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0004_auto_20200526_0733'),
        ('voluntree', '0004_interest_created_at'),
    ]

    operations = [
    ]
