# Generated by Django 3.0.6 on 2020-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0008_remove_notification_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
