# Generated by Django 3.0.6 on 2020-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0010_auto_20200527_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
