# Generated by Django 3.0.6 on 2020-06-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0011_post_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntree.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('NATION_BUILDER', 'Nation Builder')], max_length=15)),
                ('integration_data', models.TextField()),
                ('integration_access_token', models.CharField(max_length=200)),
                ('integration_expiry_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntree.Organization')),
            ],
        ),
    ]
