# Generated by Django 3.0.6 on 2020-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0012_auto_20200605_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
