# Generated by Django 3.0.6 on 2020-06-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0013_auto_20200605_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='referred_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='voluntree.Post'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='voluntree.Volunteer'),
        ),
    ]
