# Generated by Django 3.0.6 on 2020-06-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0015_verification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntree.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_volunteers', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_times', models.ManyToManyField(related_name='slots', to='voluntree.DateTime')),
            ],
        ),
        migrations.DeleteModel(
            name='PostMetaData',
        ),
        migrations.AddField(
            model_name='datetime',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_times', to='voluntree.SignUp'),
        ),
        migrations.AddField(
            model_name='post',
            name='signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='voluntree.SignUp'),
        ),
    ]
