# Generated by Django 3.0.6 on 2020-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0014_auto_20200605_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
