# Generated by Django 3.0.6 on 2020-06-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0015_auto_20200606_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='post',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='date_times',
        ),
        migrations.AlterField(
            model_name='signup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='voluntree.Organization'),
        ),
        migrations.CreateModel(
            name='DateTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeslots', to='voluntree.DateTime')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeslots', to='voluntree.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='datetimeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='voluntree.DateTimeSlot'),
        ),
    ]
