# Generated by Django 3.0.6 on 2020-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0016_auto_20200614_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
