# Generated by Django 3.0.6 on 2020-06-15 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0017_signup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
