# Generated by Django 3.0.6 on 2020-06-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0019_auto_20200615_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='datetimeslot',
        ),
        migrations.AddField(
            model_name='interest',
            name='datetime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='voluntree.DateTime'),
        ),
        migrations.AddField(
            model_name='interest',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='voluntree.Slot'),
        ),
        migrations.AddField(
            model_name='slot',
            name='date_times',
            field=models.ManyToManyField(related_name='slots', to='voluntree.DateTime'),
        ),
        migrations.DeleteModel(
            name='DateTimeSlot',
        ),
    ]
