# Generated by Django 3.0.6 on 2020-06-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0020_auto_20200615_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message_for_new_volunteer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message_for_returning_volunteer',
        ),
    ]
