# Generated by Django 3.0.6 on 2020-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0021_auto_20200617_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disabled',
        ),
        migrations.AddField(
            model_name='signup',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
