# Generated by Django 3.0.6 on 2020-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0022_auto_20200617_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='volunteer_info',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='volunteer_verification',
            field=models.BooleanField(default=True),
        ),
    ]
