# Generated by Django 3.0.6 on 2020-06-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0023_auto_20200618_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='payment_info',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='volunteer_info',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
