# Generated by Django 3.0.6 on 2020-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0024_auto_20200618_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='append_signup_info',
            field=models.BooleanField(default=False),
        ),
    ]
