# Generated by Django 3.0.6 on 2020-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0025_post_append_signup_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='nation_builder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nation_builder_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
