# Generated by Django 3.0.6 on 2020-06-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0026_auto_20200619_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerThirdPartyIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_third_party_integrations', to='voluntree.Integration')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_third_party_integrations', to='voluntree.Volunteer')),
            ],
        ),
    ]
