# Generated by Django 3.0.6 on 2020-06-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0027_volunteerthirdpartyintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='nation_builder_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='nation_builder_slug',
        ),
        migrations.AddField(
            model_name='notification',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='voluntree.SignUp'),
            preserve_default=False,
        ),
    ]
