# Generated by Django 3.0.6 on 2020-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0029_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='volunteer_info',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
