# Generated by Django 3.0.6 on 2020-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0030_auto_20200620_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='description',
            field=models.CharField(default='No description provided', max_length=1000),
            preserve_default=False,
        ),
    ]
