# Generated by Django 3.0.6 on 2020-06-22 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0031_auto_20200621_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='voluntree.SignUp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='voluntree.Volunteer')),
            ],
        ),
    ]
