# Generated by Django 3.0.6 on 2020-06-26 16:33

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0032_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Los_Angeles'),
        ),
    ]
