# Generated by Django 3.0.6 on 2020-07-13 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0034_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
