# Generated by Django 3.0.6 on 2020-07-19 12:42

from django.db import migrations, models
import voluntree.models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0035_post_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=voluntree.models.get_directory_path),
        ),
    ]
