# Generated by Django 3.0.6 on 2020-05-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='owner',
            new_name='user',
        ),
    ]
