# Generated by Django 3.0.6 on 2020-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0003_post_facebook_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='metadata',
        ),
        migrations.AddField(
            model_name='post',
            name='message_for_new_volunteer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='message_for_returning_volunteer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
