# Generated by Django 3.0.6 on 2020-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0003_post_facebook_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2012-10-20'),
            preserve_default=False,
        ),
    ]
