# Generated by Django 3.0.6 on 2020-05-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntree', '0006_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='facebook_page_id',
            field=models.CharField(default='fake-page-id', max_length=200),
            preserve_default=False,
        ),
    ]
